### ISSUE TITLE
Can't delete values in input feeld if it contains special characters

### ISSUE THREAD

**Issue by Blackfin** [s-yadav/react-number-format#548] opened 2021-06-01 06:58 UTC
#### Describe the issue and the actual behavior
Can't delete values in input feeld if it contains special characters like (-

#### Describe the expected behavior
Values in input field with special characters has been deleted

#### Provide a CodeSandbox link illustrating the issue

https://user-images.githubusercontent.com/716735/120280053-060ae080-c2d9-11eb-87de-2a155026de51.mp4

https://user-images.githubusercontent.com/716735/120280082-0efbb200-c2d9-11eb-92b9-62c16ce9bab6.MP4

#### Please check the browsers where the issue is seen
- [+ ] Chrome
- [+ ] Chrome (Android)
- [ ] Safari (OSX)
- [ +] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by nikhil-varma** [comment] 2021-06-02 12:12
Hey! Thanks for reporting this issue. We will investigate and shoot out a resolution soon. Keep an eye out for updates 🙂

**Comment by s-yadav** [comment] 2021-06-07 15:08
This is fixed on 4.6.1. 
Duplicate of #452

**Closed by s-yadav** 2021-06-07 15:08 UTC

**Comment by soarexs** [comment] 2022-10-05 21:25
Does anyone have a solution to this problem? because I still have the same issue in version 4.9.3
