### ISSUE TITLE
Undefined is not an object (evaluating 'newValue.length')

### ISSUE THREAD

**Issue by decoderid** [s-yadav/react-number-format#499] opened 2021-03-10 08:09 UTC
## [React Native]
I'm trying to use NumberFormat as TextInput in React Native app but not working.

## Expected
[https://codesandbox.io/s/aged-violet-440ef?file=/src/App.js](https://codesandbox.io/s/aged-violet-440ef?file=/src/App.js)

## Code
```es6
import React, { Component } from "react";
import NumberFormat from "react-number-format";

export default class App extends Component {
  cunstructor(props) {}

  render() {
    return (
      <NumberFormat
        decimalSeparator={","}
        thousandSeparator={"."}
        prefix={"Rp"}
      />
    );
  }
}

```

**Comment by nikhil-varma** [comment] 2021-03-10 08:14
@decoderid Thanks for reporting this. To help us investigate this further, can you please provide more information about what is not working? Maybe the error log or something else? Thanks!

**Comment by decoderid** [comment] 2021-03-10 08:30
> @decoderid Thanks for reporting this. To help us investigate this further, can you please provide more information about what is not working? Perhaps the stack trace or any other information pertaining to this? Thanks!

but this one is work for me: [#17](https://github.com/s-yadav/react-number-format/issues/17#issuecomment-401242039)

this error lead me to:

## react-number-format -> lib -> utils.js

```es6
function findChangedIndex(prevValue, newValue) {
  var i = 0,
      j = 0;
  var prevLength = prevValue.length;
  var newLength = newValue.length;

  while (prevValue[i] === newValue[i] && i < prevLength) {
    i++;
  } //check what has been changed from last


  while (prevValue[prevLength - 1 - j] === newValue[newLength - 1 - j] && newLength - j > i && prevLength - j > i) {
    j++;
  }

  return {
    start: i,
    end: prevLength - j
  };
}
```
### Error Log Without customInput={TextInput}
```LOG
03-10 15:21:06.236 25126 25177 E ReactNativeJS: Invariant Violation: View config getter callback for component `input` must be a function (received `undefined`). Make sure to start component names with a capital letter.
03-10 15:21:06.236 25126 25177 E ReactNativeJS:
03-10 15:21:06.236 25126 25177 E ReactNativeJS: This error is located at:
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in input (created by NumberFormat)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in NumberFormat (at Deposit.js:91)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at Overlay.js:23)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at Overlay.js:22)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at AppContainer.js:106)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at AppContainer.js:132)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in AppContainer (at Modal.js:220)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at Modal.js:242)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTModalHostView (at Modal.js:228)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in Modal (at Overlay.js:17)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in Overlay (at withTheme.js:38)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in Themed.Overlay (at Deposit.js:72)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at ScrollView.js:1124)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTScrollView (at ScrollView.js:1260)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in ScrollView (at ScrollView.js:1286)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in ScrollView (at Deposit.js:65)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in Deposit
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in StaticContainer
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in StaticContainer (at SceneView.tsx:115)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in EnsureSingleNavigator (at SceneView.tsx:114)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in SceneView (at useDescriptors.tsx:153)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at CardContainer.tsx:245)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at CardContainer.tsx:244)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at CardSheet.tsx:33)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in ForwardRef(CardSheet) (at Card.tsx:573)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at createAnimatedComponent.js:165)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in AnimatedComponent (at createAnimatedComponent.js:215)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in PanGestureHandler (at GestureHandlerNative.tsx:13)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in PanGestureHandler (at Card.tsx:549)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at createAnimatedComponent.js:165)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in AnimatedComponent (at createAnimatedComponent.js:215)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at Card.tsx:538)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in Card (at CardContainer.tsx:206)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in CardContainer (at CardStack.tsx:620)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at Screens.tsx:84)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in MaybeScreen (at CardStack.tsx:613)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at Screens.tsx:54)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in MaybeScreenContainer (at CardStack.tsx:495)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in CardStack (at StackView.tsx:462)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in KeyboardManager (at StackView.tsx:458)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in SafeAreaProviderCompat (at StackView.tsx:455)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at GestureHandlerRootView.android.tsx:21)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in GestureHandlerRootView (at StackView.tsx:454)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in StackView (at createStackNavigator.tsx:87)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in StackNavigator (at StackNavigator.js:80)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in HomeStackScreen (at SceneView.tsx:122)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in StaticContainer
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in StaticContainer (at SceneView.tsx:115)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in EnsureSingleNavigator (at SceneView.tsx:114)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in SceneView (at useDescriptors.tsx:153)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at BottomTabView.tsx:55)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in SceneContent (at BottomTabView.tsx:171)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at ResourceSavingScene.tsx:68)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at ResourceSavingScene.tsx:63)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in ResourceSavingScene (at BottomTabView.tsx:165)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at src/index.native.js:123)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in ScreenContainer (at BottomTabView.tsx:145)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in SafeAreaProviderCompat (at BottomTabView.tsx:144)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in BottomTabView (at createBottomTabNavigator.tsx:45)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in BottomTabNavigator (at StackNavigator.js:138)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in BottomStackScreen (at SceneView.tsx:122)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in StaticContainer
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in StaticContainer (at SceneView.tsx:115)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in EnsureSingleNavigator (at SceneView.tsx:114)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in SceneView (at useDescriptors.tsx:153)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at CardContainer.tsx:245)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at CardContainer.tsx:244)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at CardSheet.tsx:33)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in ForwardRef(CardSheet) (at Card.tsx:573)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in RCTView (at View.js:34)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in View (at createAnimatedComponent.js:165)
03-10 15:21:06.236 25126 25177 E ReactNativeJS:     in AnimatedComponent (at c
```
### Error Log With customInput={TextInput}
```LOG
03-10 15:24:41.543 25126 25177 E ReactNativeJS: TypeError: undefined is not an object (evaluating 'newValue.length')
03-10 15:24:41.690 25126 25177 E ReactNativeJS: TypeError: undefined is not an object (evaluating 'newValue.length')
03-10 15:24:41.855 25126 25177 E ReactNativeJS: TypeError: undefined is not an object (evaluating 'newValue.length')
```

**Comment by nikhil-varma** [comment] 2021-03-10 08:31
@decoderid Thanks! Can you please provide the steps to reproduce this. It will be helpful to investigate this

**Comment by nikhil-varma** [comment] 2021-03-10 14:41
@decoderid Thanks! Unfortunately we don't support React Native at the moment, the renderText workaround may not work well since handling cursor shifting could become a problem. For now, I am closing this issue. Also, #17 is open so any conversation/ideas around this can be discussed over there. Thanks again!

**Closed** 2021-03-10 14:41 UTC
