### ISSUE TITLE
Cannot type negative when value is zero

### ISSUE THREAD

**Issue by damhonglinh** [s-yadav/react-number-format#110] opened 2017-10-26 16:54 UTC
This is more like an UX issue. 

Although I can type negative number, I cannot type negative sign (`-`) when the value is 0 and negative sign is also removed automatically when the value is 0.

This is not so good to users because usually the initial value is 0 and users tend to type negative sign at first before typing any number.

Is there any option to change this behavior?

Other things work great btw!

**Comment by s-yadav** [comment] 2017-10-27 03:50
Negative with 0 does work. Can you add code here to show how you are using NumberFormat? 
Also is it with v3 or v2?

**Comment by s-yadav** [comment] 2017-11-03 04:03
Can't reproduce. Will close this. Open it again if you encounter this again.

**Closed by s-yadav** 2017-11-03 04:03 UTC

**Comment by jatwood** [comment] 2025-01-16 16:13
I ran into this as well. Here is a code sandbox URL that shows what the original bug reporter is talking about. https://codesandbox.io/p/sandbox/hardcore-tharp-nwjkcy?file=%2Fsrc%2FApp.js Basically you can't type a negative float value the intuitive way of typing "-" "0" "." "5"
