### ISSUE TITLE
Doesn't work correctly on mobile devices

### ISSUE THREAD

**Issue by Daido** [s-yadav/react-number-format#64] opened 2017-05-26 04:22 UTC
The cursor always moves to the beginning.
I've tested on Redmi Note 3 and Galaxy Tab S3

**Comment by s-yadav** [comment] 2017-05-26 05:45
@Daido  is it with latest alpha version ?

**Comment by Daido** [comment] 2017-05-26 07:05
@s-yadav I checked 1.2.1 and alpha2.

**Comment by Daido** [comment] 2017-06-12 05:50
@s-yadav Hi. Did you reproduce the problem?

**Comment by s-yadav** [comment] 2017-06-12 08:49
Couldn't reproduce this,  but have applied some patch based on #52 . Can you try once the alpha3 build?

**Comment by Daido** [comment] 2017-06-12 09:12
@s-yadav alpha3 builder work better, but there is new bug. If field already contains zero value like '0.00' and at the beginning of input you will get '10.00' instead of '1.00'

**Comment by s-yadav** [comment] 2017-06-12 09:16
Why will the field have '0.00' initially?  If user type 1 before 0.00 it's hard to identify if he actually wants to type 10.00  or 1.00.

**Comment by Daido** [comment] 2017-06-12 09:22
@s-yadav After removing value by pressing 'backspace' you will get '0.00'. If you input '1' you will get '10.00' instead of '1.0'.

**Comment by Jafferwaffer** [comment] 2017-06-15 09:23
I am experiencing the jumping caret issue on android devices with `release-1.1.2`
Just tried alpha3 build and it does fix this issue but has introduced another issue, which I think is what @Daido is describing.

For example my format mask is `#### ###### #####`
I type `4111 1111 1111 1111`
If I then type `0` I can typing any numbers after that and would appear as:
`4111 1111 1111 1111089898883` for example

This new bug I can reproduce in both desktop & mobile chrome (latest)

**Comment by s-yadav** [comment] 2017-06-16 06:00
@Jafferwaffer created a new issue for this #69

**Comment by s-yadav** [comment] 2017-06-17 06:35
@Daido created a new issue #70. The mobile issue seems to get fixed. Closing this issue.

**Closed by s-yadav** 2017-06-17 06:35 UTC
