### ISSUE TITLE
Changing value and suffix at the same time causes Maximum update depth exceeded error

### ISSUE THREAD

**Issue by AlminaHaskic** [s-yadav/react-number-format#277] opened 2019-01-30 16:17 UTC
I'm using react-number-format in combination with Formik and material-ui. I have a use case when I need to call Formiks resetForm and it updates value and a suffix at the same time. E.g. (100 m to 0 ft ). 

`const NumberFormatCustom = (props: *): NumberFormat => {
  const { inputRef, onChange, unit, ...other } = props;
  return (
    <NumberFormat
      {...other}
      getInputRef={inputRef}
      onValueChange={values => {
        onChange({
          target: {
            value: values.value,
            name: other.name,
          },
        });
      }}
      suffix={unit}
    />
  );
};`

NumberFormat is passed though InputProps to TextField.

`            InputProps={{ inputComponent: NumberFormatCustom }}
`

This is the console log that shows Maximum update depth exceeded error.

![screen shot 2019-01-30 at 5 15 00 pm](https://user-images.githubusercontent.com/22662973/51995251-a4d96500-24b2-11e9-8929-23e2689c2469.png)

**Comment by rykon** [comment] 2019-02-11 17:23
I was getting something similar -- "Maximum update depth..." message when a phone number field was autofilled by Chrome. 

I updated the `onValueChange()` function to check for the existence of the `values` object as well as the `values.formattedValue` key before calling `onChange`. This appears to have solved my problem. Hope this helps.

**Comment by AlminaHaskic** [comment] 2019-02-11 18:34
@rykon I did the same few days ago and it helps. Thank you. But still, it should be fixed in react-number-format.

**Comment by rykon** [comment] 2019-02-12 19:25
It looks like checking to see whether or not `formattedValue` is truthy before calling `onValueChange()` on [line #695](https://github.com/s-yadav/react-number-format/blob/master/src/number_format.js#L695) would fix the problem.

**Comment by s-yadav** [comment] 2019-02-13 06:29
checking formattedValue is truthy before calling onValueChange is not correct as when user press removes all the value in the input. The empty value has to be passed to the onValueChange method. 

Will check for the root cause.

**Comment by s-yadav** [comment] 2019-02-13 06:39
@AlminaHaskic @rykon Changing value and suffix at the same time works on the normal case. Can you create a codesandbox (https://codesandbox.io) with failing case. So it will be easier to debug.

**Comment by morloy** [comment] 2019-04-14 00:07
I think I found a workaround by using
```
value={this.state.value || undefined}
```

This briefly switches the component to uncontrolled if there’s now valid input and breaks the infinite loop.

**Comment by wesleyguirra** [comment] 2019-04-15 20:24
For me the problema is happening when I set name and value at onChange key:

```
<NumberFormat
      {...other}
      onValueChange={values => {
        onChange({
          target: {
            value: values.value,
            name: other.name,
          },
        });
      }}
      thousandSeparator="."
      decimalSeparator=","
      decimalScale={2}
      fixedDecimalScale
      prefix="R$"
    />
```

**Comment by yzalvov** [comment] 2019-05-12 10:00
`if (oldValue === newValue) return` before updating a state inside `onValueChange` helped me.

**Comment by alexleite** [comment] 2019-05-17 12:24
For my component, I don't call the onChange from the onValueChange. I created a internal state to change the value then to call the onChange, that solve my problem. 

You can see the code below.

```
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import NumberFormat from 'react-number-format';

const InputCurrency = (props) => {
  const {
    inputRef,
    onChange,
    prefix,
    decimalScale,
    fixedDecimalScale,
    ...other
  } = props;

  const [value, setValue] = useState(other.value);

  function handleChange(e) {
    e.target.value = value
    onChange(e);
  }

  return (
    <NumberFormat
      {...other}
      getInputRef={inputRef}
      onValueChange={(values) => {
        setValue(values.floatValue);
      }}
      value={value}
      onChange={handleChange}
      decimalScale={decimalScale}
      fixedDecimalScale={fixedDecimalScale}
      decimalSeparator=","
      thousandSeparator="."
      prefix={prefix}
    />
  );
};

InputCurrency.propTypes = {
  prefix: PropTypes.string,
  decimalScale: PropTypes.number,
  fixedDecimalScale: PropTypes.bool,
  inputRef: PropTypes.func.isRequired,
  onChange: PropTypes.func.isRequired
};

InputCurrency.defaultProps = {
  prefix: 'R$ ',
  decimalScale: 2,
  fixedDecimalScale: true
};

export default InputCurrency;

```

**Comment by petrogad** [comment] 2019-05-30 16:37
Funny, just started seeing this today when doing something like:
Pressing `2 3 5` at roughly the same time. It crashes every single time.

**Comment by jonkelling** [comment] 2019-06-21 15:18
> I think I found a workaround by using
> 
> ```
> value={this.state.value || undefined}
> ```
> 
> This briefly switches the component to uncontrolled if there’s now valid input and breaks the infinite loop.

This works for me. We found it by holding the backspace key down.

**Comment by s-yadav** [comment] 2019-06-21 15:31
If someone can create a codesandbox with failing case.

**Comment by zhusee2** [comment] 2019-07-10 07:07
I think the problem comes from L134 in `<NumberFormat>`:
https://github.com/s-yadav/react-number-format/blob/81ef1cfe38cd06b50e1e9753ff956abefead4da4/src/number_format.js#L134

When a component is re-rendered, the `props` and `prevProps` will not be the same instance, so this expression will always be `true`?

I've noticed a situation when a user types really fast, there is a chance that this component gets re-rendered (for any reason):
- **after** it calls `setState()` inside `updateValue()`  (triggered from `onChange`), but
- **before** the `setState()` callback is called (so a ancestor component gets notified of new value)

And thus the component is rendered with old value when it's controlled, and it always override its state even when the value in state is actually newer.

**Comment by simonv3** [comment] 2019-11-11 23:47
> I've noticed a situation when a user types really fast

This is what clued us in on this error - our tests were causing this loop because they type fast. Turns out a user can also trigger it. Would a better equality check fix the situation?

**Comment by zhusee2** [comment] 2019-11-12 02:51
I've proposed a possible fix over #370. Please let me know if that helps!

**Comment by s-yadav** [comment] 2020-02-20 04:06
Sorry for looking into this late. Will get the fix pushed ASAP.

**Comment by s-yadav** [comment] 2020-02-23 06:23
There is a probable fix in 4.4.1.
Closing the issue. Will reopen if the issue persists.

**Closed by s-yadav** 2020-02-23 06:23 UTC

**Comment by NicolasZim** [comment] 2021-05-28 18:36
Using 4.4.1v

Don't know if it's in fact the same reason or problem, but im having an issue about infinite loop in my component that uses NumberFormat.
If you type anything on the field, you got stuckin a loop that re-render with a new value, as if im pressing `0` on my keyboard.

You can check the demo [here](https://stackblitz.com/edit/inputmask-reactjs-typescript-2ejtzv?file=Masks%2FMaskDecimal%2Findex.tsx )
I have commented all the other custom things that i use in my project and the code only has the INTL format for start the decimal from right to left(as was discussed on #366).

Just try to type any number in the `Decimal` input field.

However, if you change the `decimalLimit` to `2` in my Decimal component you will see that code doesn't break anymore. In fact i need the `decimalLimit` with `5`.

Note: my `decmialLimit` prop works exaclty as `decimalScale` from NumberFormat.

**Comment by feslima** [comment] 2022-08-13 01:08
@MatteoGauthier @antipopp you must set the `isNumericString` as `true` and handle the change on `onValueChange` appropriately. Please, have a look at this [codesandbox](https://codesandbox.io/s/loving-smoke-ujsmz2?file=/src/App.tsx) example with `react-hook-form`. You can adapt this to Formik/whatever-controller-you-use.

Cheers!
