### ISSUE TITLE
Issues with IE

### ISSUE THREAD

**Issue by jagkum** [s-yadav/react-number-format#49] opened 2017-04-04 02:00 UTC
Thanks for creating this component with so many features. 

I found below issues with IE.

1. Can type letters if you type fast
2. Cursor point is not moving correctly if we type two numbers same time. It stays in the middle
3. This may be relate to above #2 thousand separator is in wrong position if you type numbers to fast. 

Are those known issues in your component and do you have any plan to fix them in near future? 

PS: I added pull request for negative number support(https://github.com/s-yadav/react-number-format/pull/46). Please check is it your desired behaviour

**Comment by s-yadav** [comment] 2017-04-04 03:51
No it shoudnt.  I will test it.

**Comment by jagkum** [comment] 2017-04-06 00:21
@s-yadav  Could you able to reproduce above issues in IE?

**Comment by maganuk** [comment] 2017-04-14 17:17
I was having the same issue with a normal chrome browser... slide your finger from 1 to 0 and the positions get all messed up. Fixed it by commenting out the settimeout line.

**Comment by wrabbit23** [comment] 2017-06-12 17:45
It is easy to reproduce in IE11, probably because it is slow.

![ie_cursor](https://user-images.githubusercontent.com/9598935/27047250-05ab5d10-4f6d-11e7-9e79-a2838fc67ffa.gif)

Typing too fast results in cursor getting put in the wrong place.  If your user is just powering through lots of numbers, it can cause them to enter wrong value.

**Comment by s-yadav** [comment] 2017-06-12 19:20
@wrabbit23 which version you are using. I am also seeing formatting is not properly being applied. 
I am not able to reproduce this with alpha version.

**Comment by wrabbit23** [comment] 2017-06-12 19:37
The version in my animation is whatever you have on your codepen, but we have found the issue in 2.0.0-alpha2.  I am also able to reproduce in 2.0.0-alpha3.

**Comment by wrabbit23** [comment] 2017-06-12 19:46
Looks like you have alpha3 on the codepen, so that's where I have reproduced it in the animation above.  What I'm doing it first typing 1, then (after prefix appears) typing 115 in rapid succession.  IE11 on Windows 7.

**Comment by s-yadav** [comment] 2017-06-13 05:34
Humm that's weird I can not reproduce it on browserstack with ie11 and windows7 . I might have to arrange real device. More weird is why the thousand separator is not there on your gif.

**Comment by wrabbit23** [comment] 2017-06-14 17:19
Sure, whenever you are available.  I sent you a hangout request, i think

**Comment by wrabbit23** [comment] 2017-06-15 19:13
I tried it on BrowserStack and no, I can't reproduce it there.  I think it must be something with their whole remote desktop type setup where it isn't registering as fast as it can in real browser.  No matter how fast I type it there, the interface is slow enough that it doesn't exhibit the problem.

**Comment by s-yadav** [comment] 2017-06-16 06:17
@wrabbit23 Can you try with 2.0.0-alpha4 build. It may have possible fix for this issue

**Comment by wrabbit23** [comment] 2017-06-16 14:28
I have tested alpha4 build on your codepen and it looks like you have solved it!  I will update my app and test it there as well.

https://codepen.io/s-yadav/pen/bpKNMa

@jagkum if you could test it too we can get this one closed

**Comment by s-yadav** [comment] 2017-06-17 06:29
@wrabbit23 Use alpha5 build, there was small thing i missed on alpha4 which will break on mobile devices.

**Comment by s-yadav** [comment] 2017-07-09 12:48
Fixed in 2.0.0 alpha . Reopen if it still exist

**Closed by s-yadav** 2017-07-09 12:48 UTC
