### ISSUE TITLE
Bug with cursor position on Google Pixel v7.1.2 after new release

### ISSUE THREAD

**Issue by pudgereyem** [s-yadav/react-number-format#52] opened 2017-05-01 19:53 UTC
> Update: it seems like the latest version 1.1.2 works on most devices, but non on my Google Pixel that uses 7.1.2. Version 1.0.2 works on my device, but sadly doesn't work on some other devices

## Problem
When using `format` the cursor position behaves weird on mobile.  
Here is a screencast of the problem on my Google Pixel; http://pudge.se/AznJH (recording from the codepen demo found in README)

**Comment by theseanz** [comment] 2017-05-12 21:46
I'm having this exact problem on a Nexus 5X and our QA's Samsung S6. I updated to 1.0.2 and it seems to have fixed it on my Nexus 5X, but version 1.2.0 does not work.

**Comment by pudgereyem** [comment] 2017-05-19 15:06
I've investigated this a bit, and it seems like `let cursorPos = el.selectionStart;` in the `onChangeHandler` returns the wrong thing. So after I write for example 4 in the input, `cursorPos` is still set to `0`.

This works however on 1.0.2, where refs where being used.

It happens on my device Google Pixel 7.1.2

Thoughts @s-yadav ?

**Comment by s-yadav** [comment] 2017-05-26 05:55
@pudgereyem Hey could not reproduce this on browserstack can you try the alpha version again ?

**Comment by pudgereyem** [comment] 2017-05-26 06:13
Hi @s-yadaw, I just tried on the Codepen demo and still same error. I can have a look at the changes today.

I get that it's frustrating to not be able to test the version I've reported as not working. Would be nice if we could find a solution. I'll have a look soon.

**Comment by s-yadav** [comment] 2017-05-26 06:24
Browserstack does have real device testing but can't reproduce it there either.
Have you installed some custom keyboard on your device? 
Also try the codepen again by clearing cache just to make sure old code not been cached.

**Comment by pudgereyem** [comment] 2017-05-26 09:50
@s-yadav 

Yes, it works in Browserstack for me too. But not on my actual phone. I wonder if it's the same version (7.1.2). Browserstack only say (7.1). I've also cleared the cache, didn't help.

## Recording
I pulled down the project, using `2.0.0-alpha2`, and recorded both my phone, and the Chrome Console (Remote testing). 

> I also added two lines of code that's logging `cursorPosition` in `onChangeHandler`. See screenshot; http://pudge.se/gEraYU

- Google Pixel 7.1.2: http://pudge.se/bWrX6s
- Remote Device Inspect: http://pudge.se/ci6rR

## Takeaways
1. On first input, the `cursorPos` is wrong. It returns `0` when it should be `1` 
2. On first input, the character inputed gets underlined, see screenshot; http://pudge.se/81EVaA
3. On first input, the keyboard layout is changed, why? see screenshot; http://pudge.se/81EVaA

**Comment by pudgereyem** [comment] 2017-05-30 10:06
Based on the takeaways in my comment above, I did some testing.
When changing the `type` to `tel` it works. I'm not sure why, I'll investigate this more.

ping @s-yadav

**Comment by s-yadav** [comment] 2017-05-30 10:09
I guess it has do with your soft keyboard you are using. 
Are you using any other keyboard app than native one ?

**Comment by pudgereyem** [comment] 2017-05-30 10:10
@s-yadav I use the native keyboard. What do you mean with "soft keyboard"?

**Comment by s-yadav** [comment] 2017-05-30 10:18
The mobile keyboard. Can you try logging el.selectionStart and el.selectionEnd on onChange handler.

**Comment by s-yadav** [comment] 2017-06-11 21:11
@pudgereyem Can you try alpha3 build once? I hope that's the possible fix for pixel.

**Comment by s-yadav** [comment] 2017-07-09 12:47
Fixed in 2.0.0 alpha

**Closed by s-yadav** 2017-07-09 12:47 UTC

**Comment by pudgereyem** [comment] 2017-07-10 14:52
Hi @s-yadav, this issue went away if you used `type="tel"`.
