### ISSUE TITLE
Caret moving from 0th pos to the last one

### ISSUE THREAD

**Issue by tetris0k** [s-yadav/react-number-format#154] opened 2018-02-02 13:46 UTC
Staying at the 0-th position of the input, I can press LeftArrow and move to the end of the input.
<img width="227" alt="screen shot 2018-02-02 at 16 43 39" src="https://user-images.githubusercontent.com/17045141/35736266-7845e0d2-0838-11e8-9597-aa09d79a4bf5.png">
-> Press `LeftArrow` ->
<img width="234" alt="screen shot 2018-02-02 at 16 43 53" src="https://user-images.githubusercontent.com/17045141/35736290-86271374-0838-11e8-98af-1e578c511b9c.png">

**Comment by tetris0k** [comment] 2018-02-02 13:47
Whether this is a bug or not, fixed it in the [fork](https://github.com/tetris0k/react-number-format)

**Comment by s-yadav** [comment] 2018-02-11 17:19
Is this on a specific browser. Can't reproduce it.

**Comment by tetris0k** [comment] 2018-02-12 10:00
Its case-specific and, as it appears, browser-specific. I can reproduce it in Google Chrome for 'Custom format method' use-case in your live demo

**Comment by s-yadav** [comment] 2018-03-01 07:32
Fixed on v3.2.0

**Closed by s-yadav** 2018-03-01 07:32 UTC
